/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: bszlrd (https://sketchfab.com/bszlrd)
License: CC-BY-SA-4.0 (http://creativecommons.org/licenses/by-sa/4.0/)
Source: https://sketchfab.com/3d-models/pioneer-default-cockpit-b6f4adbef70549d0852f7ed96ed0b371
Title: Pioneer Default Cockpit
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/pioneer_default_cockpit(1).glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group position={[-0.583, 0.666, -0.262]} rotation={[2.284, Math.PI / 2, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['default_cockpit-material'].geometry}
            material={materials.default_cockpit}
          />
          <group position={[0.032, 0.029, 0.05]} rotation={[Math.PI / 2, 0.741, 0]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['default_cockpit-material_1'].geometry}
              material={materials.default_cockpit}
            />
            <group rotation={[1.923, 0, 0]}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes['default_cockpit-material_2'].geometry}
                material={materials.default_cockpit}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes['default_cockpit_screen-material'].geometry}
                material={materials.default_cockpit_screen}
              />
            </group>
          </group>
        </group>
        <group position={[-0.239, 0.491, -0.654]} rotation={[3.141, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['default_cockpit-material_4'].geometry}
            material={materials.default_cockpit}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['default_cockpit-material_5'].geometry}
            material={materials.default_cockpit}
            position={[0.501, 0.153, -0.024]}
            rotation={[3.138, -0.002, -1.11]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['default_cockpit-material_6'].geometry}
            material={materials.default_cockpit}
            position={[-0.022, 0.153, -0.025]}
            rotation={[3.139, 0.004, 0.728]}
          />
        </group>
        <group position={[0, 0.476, -0.99]} rotation={[1.017, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['default_cockpit-material_8'].geometry}
            material={materials.default_cockpit}
          />
          <group position={[-0.278, 0.633, 0.053]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['default_cockpit-material_11'].geometry}
              material={materials.default_cockpit}
            />
            <group position={[0, -0.032, 0.003]}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes['default_cockpit-material_12'].geometry}
                material={materials.default_cockpit}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes['default_cockpit-material_13'].geometry}
                material={materials.default_cockpit}
                position={[-0.005, -0.012, 0.003]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes['default_cockpit-material_14'].geometry}
                material={materials.default_cockpit}
                position={[-0.028, -0.012, 0.003]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes['default_cockpit-material_15'].geometry}
                material={materials.default_cockpit}
                position={[0.023, -0.012, 0.003]}
              />
            </group>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['default_cockpit-material_16'].geometry}
              material={materials.default_cockpit}
              position={[0, -0.096, 0.003]}
            />
          </group>
          <group position={[0.279, 0.633, 0.053]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['default_cockpit-material_19'].geometry}
              material={materials.default_cockpit}
            />
            <group position={[0, 0.069, 0.003]}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes['default_cockpit-material_20'].geometry}
                material={materials.default_cockpit}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes['default_cockpit-material_21'].geometry}
                material={materials.default_cockpit}
                position={[0.027, -0.022, 0.004]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes['default_cockpit-material_22'].geometry}
                material={materials.default_cockpit}
                position={[-0.027, 0.011, 0.004]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes['default_cockpit-material_23'].geometry}
                material={materials.default_cockpit}
                position={[-0.009, 0, 0.004]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes['default_cockpit-material_24'].geometry}
                material={materials.default_cockpit}
                position={[0.009, 0.025, 0.004]}
              />
            </group>
            <group position={[0, -0.091, 0.003]}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes['default_cockpit-material_25'].geometry}
                material={materials.default_cockpit}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes['default_cockpit-material_26'].geometry}
                material={materials.default_cockpit}
                position={[0.009, 0.015, 0.002]}
                rotation={[0, 0, 0.87]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes['default_cockpit-material_27'].geometry}
                material={materials.default_cockpit}
                position={[-0.027, -0.014, 0]}
                rotation={[-0.161, 0, 0]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes['default_cockpit-material_28'].geometry}
                material={materials.default_cockpit}
                position={[-0.027, 0.015, 0.002]}
                rotation={[0, 0, -0.31]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes['default_cockpit-material_29'].geometry}
                material={materials.default_cockpit}
                position={[0.009, -0.015, 0.001]}
                rotation={[0.09, 0, 0]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes['default_cockpit-material_30'].geometry}
                material={materials.default_cockpit}
                position={[-0.009, 0.015, 0.002]}
                rotation={[0, 0, 0.395]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes['default_cockpit-material_31'].geometry}
                material={materials.default_cockpit}
                position={[-0.009, -0.014, 0]}
                rotation={[-0.161, 0, 0]}
              />
            </group>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['default_cockpit-material_32'].geometry}
              material={materials.default_cockpit}
              position={[0, -0.02, 0.003]}
            />
          </group>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['default_cockpit_screen-material_1'].geometry}
            material={materials.default_cockpit_screen}
            position={[0, 0.662, 0.053]}
            rotation={[-0.962, 0, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['default_cockpit_screen-material_2'].geometry}
            material={materials.default_cockpit_screen}
            position={[-0.278, 0.633, 0.053]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['default_cockpit-material_9'].geometry}
            material={materials.default_cockpit}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['default_cockpit-material_10'].geometry}
            material={materials.default_cockpit}
            position={[0, 0.662, 0.053]}
            scale={1.299}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['default_cockpit-material_17'].geometry}
            material={materials.default_cockpit}
            position={[0, 0.469, 0.051]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['default_cockpit-material_18'].geometry}
            material={materials.default_cockpit}
            position={[0, 0.469, 0.051]}
          />
        </group>
        <group position={[-0.271, 0.42, -0.847]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['default_cockpit-material_38'].geometry}
            material={materials.default_cockpit}
          />
          <group position={[0.543, 0, 0]} rotation={[-2.273, 0, 0]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['default_cockpit-material_39'].geometry}
              material={materials.default_cockpit}
            />
            <group position={[0, -0.15, 0.001]} rotation={[1.016, 0, 0]}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes['default_cockpit-material_40'].geometry}
                material={materials.default_cockpit}
              />
              <group position={[-0.032, -0.081, 0]} rotation={[1.254, 0, 0]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes['default_cockpit-material_41'].geometry}
                  material={materials.default_cockpit}
                />
                <group position={[0, -0.085, 0.025]}>
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes['default_cockpit-material_43'].geometry}
                    material={materials.default_cockpit}
                  />
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes['default_cockpit-material_44'].geometry}
                    material={materials.default_cockpit}
                  />
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes['default_cockpit-material_45'].geometry}
                    material={materials.default_cockpit}
                    position={[0, -0.007, 0.161]}
                    rotation={[1.45, 0, -0.208]}
                  />
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes['default_cockpit-material_46'].geometry}
                    material={materials.default_cockpit}
                    position={[-0.027, -0.009, 0.154]}
                    rotation={[1.458, 0.005, -0.208]}
                    scale={0.975}
                  />
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes['default_cockpit-material_47'].geometry}
                    material={materials.default_cockpit}
                    position={[-0.019, -0.003, 0.11]}
                    rotation={[0.495, -0.505, -0.48]}
                    scale={0.695}
                  />
                </group>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes['default_cockpit-material_42'].geometry}
                  material={materials.default_cockpit}
                  position={[0, -0.186, 0.018]}
                  rotation={[0.501, 0, 0]}
                />
              </group>
            </group>
          </group>
        </group>
        <group position={[0, -0.028, -0.852]} rotation={[2.247, Math.PI / 2, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['default_cockpit-material_48'].geometry}
            material={materials.default_cockpit}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['default_cockpit-material_49'].geometry}
            material={materials.default_cockpit}
            position={[0.066, 0.133, -0.14]}
            rotation={[-Math.PI / 2, 0.44, -Math.PI / 2]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['default_cockpit-material_50'].geometry}
            material={materials.default_cockpit}
            position={[0.187, 0.377, 0]}
            rotation={[-Math.PI / 2, 0.483, -Math.PI / 2]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['default_cockpit-material_51'].geometry}
            material={materials.default_cockpit}
            position={[0.066, 0.133, 0]}
            rotation={[-Math.PI / 2, 0.437, -Math.PI / 2]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['default_cockpit-material_52'].geometry}
            material={materials.default_cockpit}
            rotation={[-Math.PI / 2, -0.895, -Math.PI / 2]}
          />
        </group>
        <group position={[0, 0.294, -0.58]} scale={0.999}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['default_cockpit-material_53'].geometry}
            material={materials.default_cockpit}
          />
          <group
            position={[-0.6, -0.427, 0.022]}
            rotation={[-Math.PI / 2, -0.118, -Math.PI]}
            scale={1.001}>
            <lineSegments geometry={nodes.Object_137.geometry} material={materials.material_0} />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['default_cockpit-material_64'].geometry}
              material={materials.default_cockpit}
            />
          </group>
          <group position={[0.53, 0.048, 0.211]} rotation={[-2.083, -0.013, 1.919]} scale={1.001}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['default_cockpit-material_75'].geometry}
              material={materials.default_cockpit}
            />
            <group rotation={[2.158, 0, 0]}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes['default_cockpit-material_76'].geometry}
                material={materials.default_cockpit}
              />
              <group position={[0, -0.018, -0.113]} rotation={[Math.PI / 2, 0, Math.PI / 2]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes['default_cockpit-material_77'].geometry}
                  material={materials.default_cockpit}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes['default_cockpit_transp-material'].geometry}
                  material={materials.default_cockpit_transp}
                  position={[0.017, 0.078, 0.01]}
                  rotation={[-1.094, 0.001, 0]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes['default_cockpit_transp-material_1'].geometry}
                  material={materials.default_cockpit_transp}
                  position={[-0.015, 0.076, 0.009]}
                  rotation={[0.753, 0, -0.001]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes['default_cockpit-material_78'].geometry}
                  material={materials.default_cockpit}
                  position={[0.053, 0, -0.003]}
                  rotation={[0, 0, -0.003]}
                  scale={1.41}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes['default_cockpit_transp-material_2'].geometry}
                  material={materials.default_cockpit_transp}
                  position={[-0.081, 0.078, 0.01]}
                  rotation={[0.753, 0, -0.001]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes['default_cockpit_transp-material_3'].geometry}
                  material={materials.default_cockpit_transp}
                  position={[-0.048, 0.078, 0.01]}
                  rotation={[0.753, 0, -0.001]}
                />
              </group>
            </group>
          </group>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['default_cockpit-material_54'].geometry}
            material={materials.default_cockpit}
            position={[0.435, -0.423, 0.825]}
            rotation={[-2.652, -0.266, -2.719]}
            scale={1.09}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['default_cockpit-material_55'].geometry}
            material={materials.default_cockpit}
            rotation={[0.04, 0, 0]}
            scale={1.011}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['default_cockpit-material_56'].geometry}
            material={materials.default_cockpit}
            position={[-0.43, 0.563, -0.677]}
            rotation={[0.693, 0.266, -0.016]}
            scale={1.001}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['default_cockpit-material_57'].geometry}
            material={materials.default_cockpit}
            position={[-0.428, -0.154, 0.862]}
            rotation={[-2.965, 0.266, -0.016]}
            scale={1.001}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['default_cockpit-material_58'].geometry}
            material={materials.default_cockpit}
            position={[-0.611, -0.342, 0.022]}
            rotation={[-Math.PI / 2, -0.118, -Math.PI]}
            scale={1.001}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['default_cockpit-material_59'].geometry}
            material={materials.default_cockpit}
            position={[-0.6, -0.432, 0.022]}
            rotation={[-Math.PI / 2, -0.118, -Math.PI]}
            scale={1.001}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['default_cockpit-material_60'].geometry}
            material={materials.default_cockpit}
            position={[-0.43, 0.636, 0.612]}
            rotation={[2.337, 0.266, -0.016]}
            scale={1.001}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['default_cockpit-material_61'].geometry}
            material={materials.default_cockpit}
            position={[0, 0.181, 0.949]}
            rotation={[2.983, 0, Math.PI / 2]}
            scale={1.001}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['default_cockpit-material_62'].geometry}
            material={materials.default_cockpit}
            position={[-0.435, 0.808, -0.452]}
            rotation={[1.077, 0.266, -1.148]}
            scale={1.001}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['default_cockpit-material_63'].geometry}
            material={materials.default_cockpit}
            position={[0.435, 0.827, 0.421]}
            rotation={[2.058, -0.266, -2.719]}
            scale={1.001}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['default_cockpit-material_65'].geometry}
            material={materials.default_cockpit}
            position={[-0.611, -0.342, 0.022]}
            rotation={[-Math.PI / 2, -0.118, -Math.PI]}
            scale={1.001}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['default_cockpit-material_66'].geometry}
            material={materials.default_cockpit}
            position={[0.435, 0.37, -0.849]}
            rotation={[0.395, -0.258, -1.158]}
            scale={1.001}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['default_cockpit-material_67'].geometry}
            material={materials.default_cockpit}
            position={[-0.435, 0.453, 0.809]}
            rotation={[2.648, 0.266, 0.423]}
            scale={1.09}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['default_cockpit-material_68'].geometry}
            material={materials.default_cockpit}
            position={[0.43, 0.634, 0.61]}
            rotation={[2.346, -0.265, 0.019]}
            scale={1.001}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['default_cockpit-material_69'].geometry}
            material={materials.default_cockpit}
            position={[0.129, 1.215, -0.46]}
            rotation={[0.107, 0, 0]}
            scale={1.001}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['default_cockpit-material_70'].geometry}
            material={materials.default_cockpit}
            position={[0.435, 0.808, -0.452]}
            rotation={[1.077, -0.266, -1.148]}
            scale={1.001}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['default_cockpit-material_71'].geometry}
            material={materials.default_cockpit}
            position={[-0.435, 0.37, -0.849]}
            rotation={[0.404, 0.247, -1.138]}
            scale={1.001}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['default_cockpit-material_72'].geometry}
            material={materials.default_cockpit}
            position={[0.43, -0.155, 0.866]}
            rotation={[-2.965, -0.266, 0.016]}
            scale={1.001}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['default_cockpit-material_73'].geometry}
            material={materials.default_cockpit}
            position={[-0.436, -0.423, 0.826]}
            rotation={[-2.652, 0.266, -1.148]}
            scale={1.09}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['default_cockpit-material_74'].geometry}
            material={materials.default_cockpit}
            position={[0.435, 0.453, 0.81]}
            rotation={[2.648, -0.266, -2.719]}
            scale={1.09}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['default_cockpit-material_79'].geometry}
            material={materials.default_cockpit}
            position={[-0.435, 0.825, 0.42]}
            rotation={[2.058, 0.266, 0.423]}
            scale={1.001}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['default_cockpit-material_80'].geometry}
            material={materials.default_cockpit}
            position={[-0.6, -0.432, 0.022]}
            rotation={[-Math.PI / 2, -0.118, -Math.PI]}
            scale={1.001}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['default_cockpit-material_81'].geometry}
            material={materials.default_cockpit}
            scale={1.001}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['default_cockpit-material_82'].geometry}
            material={materials.default_cockpit}
            position={[0.43, 0.564, -0.678]}
            rotation={[0.693, -0.266, 0.016]}
            scale={1.001}
          />
        </group>
        <group position={[-0.289, 0.422, -0.553]} rotation={[-0.001, 1.49, Math.PI / 2]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['default_cockpit-material_83'].geometry}
            material={materials.default_cockpit}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['default_cockpit-material_84'].geometry}
            material={materials.default_cockpit}
            position={[0.002, 0.008, 0.114]}
            rotation={[0, -0.2, -0.402]}
            scale={0.789}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['default_cockpit-material_85'].geometry}
            material={materials.default_cockpit}
            position={[-0.007, -0.005, 0.112]}
            rotation={[0, -0.2, -0.402]}
            scale={0.789}
          />
        </group>
        <group position={[0.584, 0.666, -0.262]} rotation={[-2.525, -Math.PI / 2, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['default_cockpit-material_86'].geometry}
            material={materials.default_cockpit}
          />
          <group position={[-0.034, -0.03, 0.049]} rotation={[Math.PI / 2, 0.733, 0]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['default_cockpit-material_87'].geometry}
              material={materials.default_cockpit}
            />
            <group rotation={[1.915, 0, 0]}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes['default_cockpit-material_88'].geometry}
                material={materials.default_cockpit}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes['default_cockpit_screen-material_3'].geometry}
                material={materials.default_cockpit_screen}
              />
            </group>
          </group>
        </group>
        <group position={[-0.551, 0.34, -0.378]} rotation={[-2.05, -0.021, 1.221]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['default_cockpit-material_89'].geometry}
            material={materials.default_cockpit}
          />
          <group position={[0, -0.025, 0]} rotation={[-2.159, 0, 3.141]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['default_cockpit-material_90'].geometry}
              material={materials.default_cockpit}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['default_cockpit_screen-material_4'].geometry}
              material={materials.default_cockpit_screen}
              position={[0, -0.018, -0.096]}
              rotation={[Math.PI / 2, 0, -Math.PI / 2]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['default_cockpit-material_91'].geometry}
              material={materials.default_cockpit}
              position={[0, -0.018, -0.096]}
              rotation={[Math.PI / 2, 0, -Math.PI / 2]}
            />
          </group>
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['default_cockpit-material_3'].geometry}
          material={materials.default_cockpit}
          position={[-0.271, 0.42, -0.847]}
          rotation={[-2.257, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['default_cockpit-material_7'].geometry}
          material={materials.default_cockpit}
          position={[0, 0.427, -0.994]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['default_cockpit-material_33'].geometry}
          material={materials.default_cockpit}
          position={[0, 0.291, -0.591]}
          rotation={[0.049, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['default_cockpit-material_34'].geometry}
          material={materials.default_cockpit}
          position={[-0.24, 0.406, -0.628]}
          rotation={[-0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['default_cockpit-material_35'].geometry}
          material={materials.default_cockpit}
          position={[-0.271, 0.515, -0.732]}
          rotation={[1.868, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['default_cockpit-material_36'].geometry}
          material={materials.default_cockpit}
          position={[-0.239, 0.306, -0.636]}
          rotation={[0.495, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['default_cockpit-material_37'].geometry}
          material={materials.default_cockpit}
          position={[-0.239, 0.406, -0.635]}
          rotation={[-0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['default_cockpit-material_92'].geometry}
          material={materials.default_cockpit}
          position={[0.593, 0.364, -0.328]}
          rotation={[-2.525, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['default_cockpit-material_93'].geometry}
          material={materials.default_cockpit}
          position={[-0.593, 0.364, -0.328]}
          rotation={[-0.617, -Math.PI / 2, 0]}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/pioneer_default_cockpit(1).glb')
